### ISSUE TITLE
Privacy policy information is incorrect/outdated

### ISSUE THREAD

**Issue by Rey-Sol** [Transan-DT/Transan.Web#9]
When a form a form is posted in the website, the gender orientation is asked and keep in database. If we want to keep it like this we need to do 2 things. First: say it in the confidentiality policy page and secondly make it modifiable for moderator to respect the right to modify personals data.
![image](https://user-images.githubusercontent.com/81772757/113339064-3dd1c800-932a-11eb-83bf-9541cb742d8d.png)
![confitialityPolicy](https://user-images.githubusercontent.com/81772757/113339966-9190e100-932b-11eb-8e46-bf211c18f7b0.JPG)

**Comment by SakuraIsayeki** [comment]
Thank you for your report. As it turns out, this issue is larger at hand, noting massive discrepeancies and outdated information between the current Privacy Policy, and how this website proceeds with data.

As such, i'll be changing the issue to englobe all aspects of the Privacy Policy, and assigning it to the Product Owner, @MissNathanaelle.

**Comment by SakuraIsayeki** [comment]
Corrected in commit e7f4c2e32df3e50902459511fe01890e5d855499, merged on 2eaa458dcc5d524c0424b82e4343a1ee90f95914.
